// SPDX-License-Identifier: AGPL-3.0-or-later
// Desktop activity boundaries and renderer retention, against a throwaway fixture server.
const base = `http://127.0.0.1:${process.argv[2] || 3981}`;
const credentials = {username: 'smoke', password: 'smoke-admin-1'};
let response = await fetch(base + '/api/auth/setup', {method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(credentials)});
if (!response.ok) response = await fetch(base + '/api/auth/login', {method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(credentials)});
const cookie = (response.headers.get('set-cookie') || '').split(';')[0];
const api = path => fetch(base + path,{headers:{cookie}}).then(response=>response.json());
if (!cookie) throw new Error('Isolated fixture authentication failed');
const target = await (await fetch('http://127.0.0.1:9222/json/new?' + encodeURIComponent(base), {method:'PUT'})).json();
const socket = new WebSocket(target.webSocketDebuggerUrl);
await new Promise(resolve => socket.onopen = resolve);
let sequence = 0, failures = 0;
const pending = new Map(), exceptions = [], csp = [];
socket.addEventListener('message', event => {
  const message = JSON.parse(event.data);
  if (message.id) { pending.get(message.id)?.(message.result); pending.delete(message.id); }
  if (message.method === 'Runtime.exceptionThrown') exceptions.push(message.params.exceptionDetails.text);
  if (message.method === 'Log.entryAdded' && message.params.entry.source === 'security') csp.push(message.params.entry.text);
});
const send = (method,params={}) => new Promise(resolve => {pending.set(++sequence,resolve);socket.send(JSON.stringify({id:sequence,method,params}));});
const js = async expression => (await send('Runtime.evaluate',{expression,returnByValue:true})).result?.value;
const sleep = ms => new Promise(resolve => setTimeout(resolve,ms));
const check = (label,ok) => {console.log(`${ok?'PASS':'FAIL'} ${label}`);if(!ok)failures++;};
async function wait(expression) { for(let i=0;i<50;i++){if(await js(expression))return true;await sleep(100);}return false; }
const click = expression => js(`${expression}?.click()`);
async function screenshot(name) {
  if(!process.env.MUSICATA_UI_SCREENSHOTS)return;
  const {mkdir,writeFile}=await import('node:fs/promises');
  await mkdir(process.env.MUSICATA_UI_SCREENSHOTS,{recursive:true});
  const {data}=await send('Page.captureScreenshot',{format:'png'});
  await writeFile(`${process.env.MUSICATA_UI_SCREENSHOTS}/${name}.png`,Buffer.from(data,'base64'));
}
await send('Runtime.enable');await send('Log.enable');await send('Network.enable');
await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
await send('Network.setCookie',{name:'musicata_session',value:cookie.slice(cookie.indexOf('=')+1),domain:'127.0.0.1',path:'/'});
await send('Page.reload');
if(!await wait(`document.querySelectorAll('.album-card').length === 6`))throw new Error('Fixture library did not load');
check('Browse, Listen and Settings are separate activities',await js(`['browse','listen','settings'].every(area=>document.querySelector('[data-activity="'+area+'"]'))`));
await screenshot('browse');
// Start real browser playback, then keep the exact audio element as a reference.
await click(`[...document.querySelectorAll('.seg')].find(button=>button.textContent.trim()==='Tracks')`);
await wait(`document.querySelector('.track-play')`);
await click(`document.querySelector('.track-play')`);
check('fixture is actually playing before navigation',await wait(`document.querySelector('audio')?.currentTime > 0 && !document.querySelector('audio').paused`));
await click(`document.querySelector('.eq-btn[title="Equalizer"]')`);
await js(`(()=>{const select=document.querySelector('.right-rail .eq-field select:not(.leveling-select)');if(select){select.value='demo-bass';select.dispatchEvent(new Event('change',{bubbles:true}));}})()`);
check('a real EQ profile is active before profile management',await wait(`document.querySelector('.right-rail .eq-band')`));
await click(`document.querySelector('.eq-btn[title="Equalizer"]')`);
await js(`window.activityAudio=document.querySelector('audio');window.activityTitle=document.querySelector('#now-title').textContent;window.activityPosition=activityAudio.currentTime;`);
await click(`document.querySelector('[data-activity="settings"]')`);
check('Settings opens within the player document',await wait(`document.querySelector('[data-settings]')`));
check('Settings offers categories without browse segments',await js(`document.querySelectorAll('[data-settings-category]').length===6 && !document.querySelector('.segmented') && !document.querySelector('.library-panel .browse-filters')`));
check('audio and transport survive opening Settings',await js(`document.querySelector('audio')===window.activityAudio && !activityAudio.paused && document.querySelector('#now-title').textContent===activityTitle`));
await js(`(()=>{const input=document.querySelector('[data-settings-search]');if(input){input.value='scrobbling';input.dispatchEvent(new Event('input',{bubbles:true}));}})()`);
check('search finds a setting with its category',await wait(`document.querySelector('[data-settings-results]')?.textContent.includes('Scrobbling') && document.querySelector('[data-settings-results]')?.textContent.includes('History & services')`));
check('settings tabs keep valid accessibility targets during search',await js(`[...document.querySelectorAll('[data-settings-category][aria-controls]')].every(tab=>document.getElementById(tab.getAttribute('aria-controls')))`));
await click(`document.querySelector('[data-settings-results] button')`);
check('search opens the matching category',await wait(`document.querySelector('[data-settings-category="history"]')?.getAttribute('aria-selected')==='true' && document.querySelector('[data-settings-panel="history"]')?.textContent.includes('Scrobbling')`));
await js(`(()=>{const input=document.querySelector('[data-settings-search]');if(input){input.value='not-a-real-setting';input.dispatchEvent(new Event('input',{bubbles:true}));}})()`);
check('settings search has a useful empty state',await wait(`document.querySelector('[data-settings-results]')?.textContent.includes('No settings found')`));
await click(`document.querySelector('[data-settings-category="sound"]')`);
check('profile management is in Settings',await wait(`document.querySelector('[data-profile-management]')`));
const browserOutput=(await api('/api/players')).find(output=>output.kind==='browser');
const initialDsp=await api(`/api/players/${browserOutput.id}/dsp`);
await js(`(()=>{const name=document.querySelector('[placeholder="Preset name (e.g. HD 600)"]');const text=document.querySelector('.eq-text');if(name&&text){name.value='Activity imported profile';name.dispatchEvent(new Event('input',{bubbles:true}));text.value='Preamp: -3 dB\\nFilter 1: ON LS Fc 100 Hz Gain 3 dB Q 0.7';text.dispatchEvent(new Event('input',{bubbles:true}));[...document.querySelectorAll('[data-profile-management] button')].find(button=>button.textContent.trim()==='Save profile')?.click();}})()`);
check('profile import is saved',await wait(`document.querySelector('[data-profile-management]')?.textContent.includes('Activity imported profile')`));
const afterImport=await api(`/api/players/${browserOutput.id}/dsp`);
check('import preserves the current output selection',initialDsp.selection.profile_id==='demo-bass' && JSON.stringify(initialDsp.selection)===JSON.stringify(afterImport.selection));
await js(`(()=>{const manager=document.querySelector('[data-profile-management]');const name=manager.querySelector('[placeholder="Preset name (e.g. HD 600)"]');const text=manager.querySelector('.eq-text');name.value='Invalid import';name.dispatchEvent(new Event('input',{bubbles:true}));text.value='Preamp: -100 dB\\nFilter 1: ON LS Fc 100 Hz Gain 3 dB Q 0.7';text.dispatchEvent(new Event('input',{bubbles:true}));[...manager.querySelectorAll('button')].find(button=>button.textContent.trim()==='Save profile').click();})()`);
check('rejected import explains the failure in Settings',await wait(`document.querySelector('[data-profile-management] .eq-error')?.textContent.length > 0`));
check('rejected import does not claim a successful save',await js(`!document.querySelector('[data-profile-management] [role=status]')`));
await screenshot('settings-sound');
await click(`document.querySelector('.eq-btn[title="Equalizer"]')`);
check('quick sound controls omit profile creation and import',await wait(`document.querySelector('.right-rail .eq-drawer') && !document.querySelector('.right-rail .eq-drawer .eq-import')`));
check('quick sound controls separate correction and listening adjustment',await js(`!!document.querySelector('.right-rail [data-correction-select]') && !!document.querySelector('.right-rail [data-listening-select]') && !!document.querySelector('.right-rail [data-correction-enabled]') && !!document.querySelector('.right-rail [data-listening-enabled]')`));
const imported=(await api('/api/dsp/profiles')).find(profile=>profile.name==='Activity imported profile');
await js(`(()=>{const select=document.querySelector('.right-rail .eq-field select:not(.leveling-select)');select.value=${JSON.stringify(imported?.id)};select.dispatchEvent(new Event('change',{bubbles:true}));})()`);
await sleep(400);
const activeImported=await api(`/api/players/${browserOutput.id}/dsp`);
await js(`(()=>{const manager=document.querySelector('[data-profile-management]');const name=manager.querySelector('.eq-import input[placeholder="Preset name (e.g. HD 600)"]');const text=manager.querySelector('.eq-text');name.value='Activity imported profile';name.dispatchEvent(new Event('input',{bubbles:true}));text.value='Preamp: -6 dB\\nFilter 1: ON LS Fc 100 Hz Gain 6 dB Q 0.7';text.dispatchEvent(new Event('input',{bubbles:true}));[...manager.querySelectorAll('button')].find(button=>button.textContent.trim()==='Save profile').click();})()`);
await sleep(500);
const profilesAfterRepeat=await api('/api/dsp/profiles');
check('re-import creates a separate profile without overwriting active correction',!!imported && activeImported.selection.profile_id===imported.id && profilesAfterRepeat.filter(profile=>profile.name==='Activity imported profile').length===2 && profilesAfterRepeat.find(profile=>profile.id===imported.id)?.preampDb===-3 && (await api(`/api/players/${browserOutput.id}/dsp`)).selection.profile_id===imported.id);
await js(`(()=>{const select=document.querySelector('.right-rail [data-listening-select]');select.value='taste-techno-bass';select.dispatchEvent(new Event('change',{bubbles:true}));})()`);
check('listening adjustment composes with correction on the browser renderer',await wait(`document.querySelector('.right-rail .eq-band-head')?.textContent.includes('Preamp -7.0 dB') && document.querySelector('.right-rail .eq-band-head')?.textContent.includes('2 bands') && [...document.querySelectorAll('.right-rail .eq-note')].some(note=>note.textContent.toLowerCase().includes('applied'))`));
const bothLayers=await api(`/api/players/${browserOutput.id}/dsp`);
check('both layers keep their independent identities',bothLayers.selection.profile_id===imported.id && bothLayers.selection.listening_profile_id==='taste-techno-bass' && bothLayers.selection.correction_enabled && bothLayers.selection.listening_enabled && bothLayers.selection.enabled);
check('composition leaves stored correction untouched',(await api('/api/dsp/profiles')).find(profile=>profile.id===imported.id)?.bands.length===1);
await click(`document.querySelector('.right-rail [data-correction-enabled]')`);
check('correction can be bypassed while the listening adjustment remains audible',await wait(`document.querySelector('.right-rail .eq-band-head')?.textContent.includes('Preamp -4.0 dB') && document.querySelector('.right-rail .eq-band-head')?.textContent.includes('1 band')`));
const toneOnly=await api(`/api/players/${browserOutput.id}/dsp`);
check('correction bypass preserves both selected profiles',!toneOnly.selection.correction_enabled && toneOnly.selection.enabled && toneOnly.selection.profile_id===imported.id && toneOnly.selection.listening_profile_id==='taste-techno-bass');
await click(`document.querySelector('.right-rail [data-correction-enabled]')`);
await js(`(()=>{const select=document.querySelector('.right-rail [data-listening-select]');select.value='';select.dispatchEvent(new Event('change',{bubbles:true}));})()`);
check('Neutral removes only the listening adjustment',await wait(`document.querySelector('.right-rail .eq-band-head')?.textContent.includes('Preamp -3.0 dB')`));
const neutral=await api(`/api/players/${browserOutput.id}/dsp`);
check('Neutral preserves equipment correction',neutral.selection.profile_id===imported.id && neutral.selection.correction_enabled && !neutral.selection.listening_enabled && neutral.selection.listening_profile_id===null);
await screenshot('sound-layers');
await click(`document.querySelector('.eq-btn[title="Equalizer"]')`);
await click(`document.querySelector('[data-activity="listen"]')`);
check('Listen contains Queue, Playlists, Mixes and Stations',await wait(`['Queue','Playlists','Mixes','Stations'].every(label=>[...document.querySelectorAll('[data-listen-tab]')].some(button=>button.textContent.trim()===label))`));
check('browsing labels are absent from Listen',await js(`!document.querySelector('.content .segmented')`));
check('Listen queue stays inside its content area and leaves navigation clickable',await js(`(()=>{const content=document.querySelector('.content').getBoundingClientRect();const queue=document.querySelector('.content .queue-drawer')?.getBoundingClientRect();const button=document.querySelector('[data-activity="settings"]');const bounds=button.getBoundingClientRect();return !!queue && queue.left>=content.left && queue.right<=content.right && button.contains(document.elementFromPoint(bounds.x+bounds.width/2,bounds.y+bounds.height/2));})()`));
await screenshot('listen');
await send('Page.enable');await js('history.back()');
check('Back restores Settings',await wait(`document.querySelector('[data-settings]')`));
await js('history.forward()');
check('Forward restores Listen',await wait(`document.querySelector('[data-listen-tab]')`));
await sleep(500);
check('navigation keeps real audio progressing',await js(`document.querySelector('audio')===activityAudio && !activityAudio.paused && activityAudio.currentTime>activityPosition`));
check('no uncaught application exceptions',exceptions.length===0);
check('no CSP violations',csp.length===0);
// A listener can control playback but cannot expose or execute administration actions.
const listener = {username:'activity-listener',password:'activity-listener-1',role:'listener'};
const created = await fetch(base+'/api/users',{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify(listener)});
if(!created.ok)throw new Error('Could not create isolated listener account');
const login=await fetch(base+'/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(listener)});
const listenerCookie=(login.headers.get('set-cookie')||'').split(';')[0];
check('listener administration API access is denied',(await fetch(base+'/api/settings',{headers:{cookie:listenerCookie}})).status===403);
await send('Network.setCookie',{name:'musicata_session',value:listenerCookie.slice(listenerCookie.indexOf('=')+1),domain:'127.0.0.1',path:'/'});
const legacyProfile={id:'legacy-listener-correction',name:'Legacy listener correction',kind:'headphones',preampDb:-2,bands:[{type:'peaking',freq:1000,gain:2,q:1}]};
await js(`localStorage.setItem('musicata-dsp',${JSON.stringify(JSON.stringify({enabled:true,activeId:legacyProfile.id,custom:[legacyProfile]}))})`);
await send('Page.navigate',{url:base+'/'});
check('listener can browse without administration controls',await wait(`document.querySelector('[data-activity="browse"]') && !document.querySelector('[data-activity="settings"]') && !document.querySelector('[data-settings]')`));
await click(`document.querySelector('.eq-btn[title="Equalizer"]')`);
check('legacy listener profiles remain stored with an administrator-import explanation',await wait(`document.querySelector('.right-rail [role=alert]')?.textContent.includes('administrator') && JSON.parse(localStorage.getItem('musicata-dsp')).custom?.some(profile=>profile.id==='legacy-listener-correction')`));
await js(`document.querySelector('.right-rail .leveling-select').value='track';document.querySelector('.right-rail .leveling-select').dispatchEvent(new Event('change',{bubbles:true}))`);
check('changing listener preferences preserves pending legacy profiles',await js(`JSON.parse(localStorage.getItem('musicata-dsp')).custom?.some(profile=>profile.id==='legacy-listener-correction')`));
await send('Page.navigate',{url:base+'/admin'});
check('direct admin entry denies listeners',await wait(`document.body.textContent.includes('Administrator access required') && !document.querySelector('[data-settings]')`));
await send('Network.setCookie',{name:'musicata_session',value:cookie.slice(cookie.indexOf('=')+1),domain:'127.0.0.1',path:'/'});
await send('Page.navigate',{url:base+'/'});
check('administrator login completes the preserved legacy profile import',await wait(`document.querySelector('[data-activity="settings"]') && !JSON.parse(localStorage.getItem('musicata-dsp')).custom?.length`) && (await api('/api/dsp/profiles')).some(profile=>profile.id===legacyProfile.id));
socket.close();process.exit(failures?1:0);
