// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who this instance is and where to get its source. **Open** (no session required): AGPL
 * section 13 entitles everyone who reaches Musicata over the network to its source, which
 * includes visitors sitting at the login screen, so the offer cannot live behind auth.
 */
export type About = { name: string, version: string, 
/**
 * Commit this binary was built from; empty when the build had no git checkout.
 */
commit: string, license: string, 
/**
 * Where to get *this* instance's source — operator-configurable in /admin.
 */
source_url: string, };
