// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Activity = { id: number, 
/**
 * Coarse category, e.g. "scan".
 */
kind: string, 
/**
 * Human-readable description, updated as the work progresses.
 */
label: string, 
/**
 * "running" | "ok" | "error".
 */
status: string, started_at_unix_seconds: number, finished_at_unix_seconds: number | null, 
/**
 * Result summary, or the failure with its root cause.
 */
message: string | null, };
