// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Album = { id: string, title: string, artist_id: string, artist_name: string, year: number | null, track_count: number, artwork_url: string | null, };
