// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * List configured sources: the always-present local library plus any persisted
 * network sources (SMB shares).
 * User-editable app settings (the `/admin` Settings panel; persisted in the DB).
 */
export type AppSettings = { 
/**
 * Automatically fetch missing album covers from external providers.
 */
artwork_fetch: boolean, 
/**
 * Optional fanart.tv personal API key (empty = unset).
 */
fanart_tv_key: string, 
/**
 * Identify untagged tracks by audio fingerprint (AcoustID) to resolve MusicBrainz
 * ids, which the id-exact artwork providers then use.
 */
fingerprint_enabled: boolean, 
/**
 * Apply real MusicBrainz metadata (title/artist/album/track number) to fingerprinted
 * tracks, without overwriting embedded tags. DB-only; files are never modified.
 */
musicbrainz_enrich_enabled: boolean, };
