// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A group of artist-name variants merged under one canonical artist.
 */
export type ArtistAliasGroup = { canonical_key: string, canonical_name: string, 
/**
 * The normalized keys of the merged-in members.
 */
members: Array<string>, };
