// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Artist = { id: string, name: string, album_count: number, track_count: number, 
/**
 * Served URL for an externally-acquired artist image, or `None` (the UI shows a
 * monogram). Set by the artwork fill pass, not by the scanner.
 */
artwork_url: string | null, };
