// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticExportStatus } from "./DiagnosticExportStatus";
import type { DiagnosticHealth } from "./DiagnosticHealth";

export type DiagnosticStatus = { health: DiagnosticHealth, export: DiagnosticExportStatus, };
