// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiagnosticHealth = { available: boolean, database_bytes: number, wal_bytes: number, dropped_events: number, rejected_events: number, detail_remaining_seconds: number, storage_gaps: number, reported_lost_events: number, };
