// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A normalized directory station for the UI (distinct from a saved `RadioStation`).
 */
export type DirectoryStation = { name: string, stream_url: string, homepage_url: string | null, favicon: string | null, country: string | null, tags: string | null, codec: string | null, bitrate: number, };
