// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DspBand = { 
/**
 * "peaking" | "lowshelf" | "highshelf".
 */
type: string, freq: number, gain: number, q: number, };
