// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DspBand } from "./DspBand";
import type { RoomIr } from "./RoomIr";

export type DspProfile = { id: string, name: string, 
/**
 * Preamp / headroom in dB (applied as a front gain so band boosts don't clip).
 */
preampDb: number, bands: Array<DspBand>, 
/**
 * "headphones" | "speakers" — drives the output switcher + which profiles can carry a room IR.
 */
kind: string | null, roomIr: RoomIr | null, };
