// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LibrarySummary = { provider_id: string, source_root: string, artist_count: number, album_count: number, track_count: number, };
