// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MeasurementPoint = "browser_output" | "native_output" | "snapcast_stream" | "camilladsp_playback";
