// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetadataApprovalState } from "./MetadataApprovalState";
import type { MetadataFieldValue } from "./MetadataFieldValue";

export type MetadataFieldReviewUpdate = { source: string, observed_at_unix_seconds: number, field_name: string, value: MetadataFieldValue, approval_state: MetadataApprovalState, };
