// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetadataApprovalState } from "./MetadataApprovalState";
import type { TrackMetadataFieldObservation } from "./TrackMetadataFieldObservation";

export type MetadataObservationReviewResponse = { source: string, confidence: number, observed_at_unix_seconds: number, approval_state: MetadataApprovalState, fields: Array<TrackMetadataFieldObservation>, };
