// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MetadataFieldValue = { "kind": "text", "value": string } | { "kind": "number", "value": number } | { "kind": "text_list", "value": Array<string> } | { "kind": "count", "value": number };
