// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OutputDspSelection = { profile_id: string | null, enabled: boolean, correction_enabled: boolean, listening_profile_id: string | null, listening_enabled: boolean, };
