// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioCapabilities } from "./AudioCapabilities";
import type { DspStatus } from "./DspStatus";
import type { MeasurementPoint } from "./MeasurementPoint";
import type { OutputDspSelection } from "./OutputDspSelection";

export type OutputDspState = { output_id: string, configured: boolean, session_id: string, selection: OutputDspSelection, desired_revision: number, applied_revision: number | null, status: DspStatus, error: string | null, capabilities: AudioCapabilities, measurement_point: MeasurementPoint, };
