// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaybackStatus } from "./PlaybackStatus";
import type { QueueItem } from "./QueueItem";
import type { RepeatMode } from "./RepeatMode";

export type PlaybackState = { status: PlaybackStatus, now_playing: QueueItem | null, elapsed_seconds: number | null, duration_seconds: number | null, volume: number | null, repeat: RepeatMode, shuffle: boolean, queue: Array<QueueItem>, queue_position: number | null, 
/**
 * The track the server will play next, given the current repeat/shuffle order — a hint
 * for clients that prefetch (the native endpoint's gapless playback). `None` when the
 * next item can't be predicted (end of a shuffle cycle, or the queue stops at the end).
 */
next_up: QueueItem | null, };
