// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaybackStatus } from "./PlaybackStatus";
import type { QueueItem } from "./QueueItem";
import type { RepeatMode } from "./RepeatMode";

export type PlaybackState = { status: PlaybackStatus, now_playing: QueueItem | null, elapsed_seconds: number | null, duration_seconds: number | null, volume: number | null, repeat: RepeatMode, shuffle: boolean, queue: Array<QueueItem>, queue_position: number | null, };
