// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What transport features a player backend supports, advertised per player so a
 * controller skips controls a backend can't honour (e.g. a future bridged endpoint
 * that can't edit its queue). Mirrors [`ProviderCapabilities`] for sources.
 */
export type PlayerCapabilities = { seek: boolean, volume: boolean, repeat: boolean, shuffle: boolean, queue: boolean, };
