// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerCapabilities } from "./PlayerCapabilities";

export type Player = { id: string, name: string, 
/**
 * Backend kind, e.g. "mpd".
 */
kind: string, 
/**
 * Backend address the server connects to, e.g. `host:port` for MPD.
 */
address: string, 
/**
 * Zone this player belongs to, if any.
 */
zone_id: string | null, online: boolean, capabilities: PlayerCapabilities, };
