// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a music source is able to do. Sources are deliberately uneven: a local
 * folder or an SMB share can be scanned and searched, while an internet-radio
 * source can only stream. Each provider advertises its capabilities so the API
 * and UI can hide affordances a source does not support.
 */
export type ProviderCapabilities = { 
/**
 * Can enumerate its whole catalogue into the merged library (`scan`).
 */
can_scan: boolean, 
/**
 * Can be navigated hierarchically without a full scan.
 */
can_browse: boolean, 
/**
 * Can answer text searches against its own catalogue.
 */
can_search: boolean, 
/**
 * Can produce a playable audio stream for its items.
 */
can_stream: boolean, };
