// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a controller knows about a track queued on a player. `stream_url` is what
 * the player actually fetches; `track_id` links back to the library when known.
 */
export type QueueItem = { track_id: string | null, title: string, artist: string, album: string, stream_url: string, artwork_url: string | null, };
