// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An internet radio station — a named external stream. The first non-library music
 * source (see docs/plugins.md).
 */
export type RadioStation = { id: string, name: string, stream_url: string, homepage_url: string | null, created_at_unix_seconds: bigint, };
