// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `sampleRate` of a stored room impulse response (the WAV bytes live in a file served by
 * `/api/dsp/profiles/{id}/impulse`; see Phase 4).
 */
export type RoomIr = { sampleRate: number, };
