// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A provisioned room as shown in `/admin`: its name, the snapclient command (password
 * embedded), and whether a snapclient with that name is currently connected.
 */
export type SnapRoomView = { name: string, command: string, connected: boolean, };
