// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A snapclient as snapserver sees it — one synchronized output (a room/speaker).
 */
export type SnapClient = { id: string, name: string, connected: boolean, volume_percent: number, muted: boolean, };
