// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SnapClient } from "./SnapClient";

export type SnapcastStatus = { 
/**
 * Persisted enable flag (a disable takes full effect on restart).
 */
enabled: boolean, 
/**
 * Whether the managed snapserver + player are actually running this session.
 */
running: boolean, 
/**
 * Connected snapclients (rooms), each a synchronized output.
 */
clients: Array<SnapClient>, };
