// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A snapserver stream (the Musicata library stream, or an AirPlay/Spotify input).
 */
export type SnapStream = { id: string, 
/**
 * snapserver stream status: usually `"playing"` or `"idle"`.
 */
status: string, 
/**
 * "Artist — Title" from the stream's metadata, when it carries any (AirPlay/Spotify do).
 */
now_playing: string | null, };
