// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SnapClient } from "./SnapClient";
import type { SnapStream } from "./SnapStream";

export type SnapcastStatus = { 
/**
 * Persisted enable flag (a disable takes full effect on restart).
 */
enabled: boolean, 
/**
 * Whether the managed snapserver + player are actually running this session.
 */
running: boolean, 
/**
 * Persisted "require a per-room password" flag. **Not enforced by snapserver 0.35** (auth
 * is stubbed upstream) — the UI says so; it's forward-compatible config.
 */
auth_enabled: boolean, 
/**
 * The address rooms dial (shown in each room's install command).
 */
server_host: string, 
/**
 * Connected snapclients (rooms), each a synchronized output.
 */
clients: Array<SnapClient>, 
/**
 * Streams snapserver currently has live (Musicata + any enabled inputs) with now-playing.
 */
inputs: Array<SnapStream>, 
/**
 * Which stream all rooms are currently playing (`Musicata`/`AirPlay`/`Spotify`).
 */
active_input: string, 
/**
 * Cast-in input config (the toggles + whether the helper binary is installed).
 */
airplay_enabled: boolean, airplay_installed: boolean, spotify_enabled: boolean, spotify_installed: boolean, };
