// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderCapabilities } from "./ProviderCapabilities";

export type SourceView = { id: string, kind: string, display_name: string, enabled: boolean, capabilities: ProviderCapabilities, };
