// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StereoLevels = { rms_l: number, rms_r: number, peak_l: number, peak_r: number, };
