// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetadataObservationReviewResponse } from "./MetadataObservationReviewResponse";
import type { TrackCanonicalMetadataResponse } from "./TrackCanonicalMetadataResponse";

export type TrackMetadataReviewResponse = { track_id: string, canonical: TrackCanonicalMetadataResponse, observations: Array<MetadataObservationReviewResponse>, };
