// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetadataApprovalState } from "./MetadataApprovalState";
import type { MetadataFieldValue } from "./MetadataFieldValue";

export type TrackMetadataFieldObservation = { source: string, field_name: string, value: MetadataFieldValue, confidence: number, observed_at_unix_seconds: number, approval_state: MetadataApprovalState, };
