// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A named group of players. Commands sent to a zone apply to its players; there
 * is no audio synchronization between them.
 */
export type Zone = { id: string, name: string, };
