// Typed client for the server's JSON API. The response types are generated from the Rust
// wire structs by ts-rs (see ../types/, regenerated by scripts/gen-web-types.sh), so a
// server-side shape change surfaces here as a TypeScript error.
//
// Coverage grows with the migration: types are generated as each view is ported. Track /
// Player / PlaybackState and the rest land with their components (phases 2–3).
import type { LibrarySummary } from "../types/LibrarySummary";
import type { Artist } from "../types/Artist";
import type { Album } from "../types/Album";
import type { Zone } from "../types/Zone";
import type { RadioStation } from "../types/RadioStation";

/** Server pagination envelope (`Page<T>` in main.rs). Hand-typed — ts-rs doesn't export the
 *  generic wrapper; the element type is generated. */
export interface Page<T> {
  items: T[];
  total: number;
  limit: number;
  offset: number;
  sort: string | null;
}

// A `type` (not `interface`) so it carries an implicit index signature and is accepted
// where a `Record<string, ...>` of query params is expected.
export type ListParams = {
  limit?: number;
  offset?: number;
  sort?: string;
};

export class ApiError extends Error {
  constructor(
    readonly status: number,
    message: string,
  ) {
    super(message);
    this.name = "ApiError";
  }
}

async function getJson<T>(
  path: string,
  params?: Record<string, string | number | undefined>,
): Promise<T> {
  const url = new URL(path, location.origin);
  for (const [key, value] of Object.entries(params ?? {})) {
    if (value !== undefined) url.searchParams.set(key, String(value));
  }
  const response = await fetch(url, { headers: { accept: "application/json" } });
  if (!response.ok) throw new ApiError(response.status, `GET ${path} → ${response.status}`);
  return (await response.json()) as T;
}

export const api = {
  librarySummary: () => getJson<LibrarySummary>("/api/library/summary"),
  artists: (params?: ListParams) => getJson<Page<Artist>>("/api/artists", params),
  albums: (params?: ListParams) => getJson<Page<Album>>("/api/albums", params),
  zones: () => getJson<Zone[]>("/api/zones"),
  radio: () => getJson<RadioStation[]>("/api/radio"),
};
