# SPDX-License-Identifier: AGPL-3.0-or-later
FROM caddy:2-builder-alpine@sha256:096ec6e825e219175bd5be64b5e7a4000977f701a2bcaab825621d9fb1e1154b AS builder
RUN GOSUMDB=sum.golang.org GOPROXY=https://proxy.golang.org xcaddy build v2.11.7 --with github.com/caddy-dns/cloudflare@v0.2.4

FROM caddy:2-alpine@sha256:d44355d3c2149dc580ce2cac735955d1c08d3d00882c30489c241aa51a5c10d9
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
RUN setcap cap_net_bind_service=+ep /usr/bin/caddy \
    && caddy version | grep -q '^v2.11.7 ' \
    && caddy list-modules | grep -qx dns.providers.cloudflare
